version: '3.8'

services:
  wordpress:
    build:
      context: .
      args:
        - NO_CACHE=${NO_CACHE}
    ports:
      - "${WP_PORT}:80"
    volumes:
      - ./wordpress/:/var/www/html
      - ./start.sh:/usr/local/bin/start.sh
    entrypoint: ["start.sh"]

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
